name: Publish Python 🐍 distributions 📦 to PyPI
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          python_version: "3.9.17"
          poetry_install_options: "--without dev"
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
